print("Добро пожаловать в самый простой калькулятор площади и периметра!")
lenght = int(input("Введите длинну: "))
height = int(input("Введите высоту: "))
print("Периметр равен:", 2 * (lenght + height))
print("Площадь равна:", lenght * height)